# -*- coding: utf-8 -*-
"""Telecom churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EzqLLxw0M1T0GSOlHXg2eclo3aN_SST7
"""

#Step 1: Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Step 2: Upload the dataset
from google.colab import files

uploaded = files.upload()

#Load the dataset
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

#Understand the dataset
print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

#Check basic statistics
df.describe()

#Check missing values
print(df.isnull().sum())

#Convert TotalCharges to numeric
df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

print(df["TotalCharges"].isnull().sum())

#Check and remove duplicates
print("Duplicate Rows:", df.duplicated().sum())

#Check unique values
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    print("\n", column)
    print(df[column].unique())

#Convert SeniorCitizen to readable values
df["SeniorCitizen"] = df["SeniorCitizen"].map({
    0: "No",
    1: "Yes"
})

df["SeniorCitizen"].value_counts()

#Create tenure groups

#This makes customer retention analysis easier.

def tenure_group(tenure):
    if tenure <= 12:
        return "0-1 Year"
    elif tenure <= 24:
        return "1-2 Years"
    elif tenure <= 48:
        return "2-4 Years"
    else:
        return "4+ Years"

df["TenureGroup"] = df["tenure"].apply(tenure_group)

df["TenureGroup"].value_counts()

#Total customers
total_customers = df["customerID"].nunique()

print("Total Customers:", total_customers)

#Churned customers
churned_customers = df[df["Churn"] == "Yes"]["customerID"].nunique()

print("Churned Customers:", churned_customers)

#Retained customers
retained_customers = df[df["Churn"] == "No"]["customerID"].nunique()

print("Retained Customers:", retained_customers)

#Churn rate
churn_rate = (
    churned_customers / total_customers
) * 100

print("Churn Rate:", round(churn_rate, 2), "%")

#Retention rate
retention_rate = (
    retained_customers / total_customers
) * 100

print("Retention Rate:", round(retention_rate, 2), "%")

#Average monthly charges
average_monthly_charges = df["MonthlyCharges"].mean()

print(
    "Average Monthly Charges:",
    round(average_monthly_charges, 2)
)

#eda
#Churn distribution
churn_counts = df["Churn"].value_counts()

print(churn_counts)

plt.figure(figsize=(6, 5))

sns.countplot(
    data=df,
    x="Churn"
)

plt.title("Customer Churn Distribution")
plt.xlabel("Churn")
plt.ylabel("Number of Customers")
plt.show()

#Churn by contract type
contract_churn = pd.crosstab(
    df["Contract"],
    df["Churn"]
)

print(contract_churn)

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x="Contract",
    hue="Churn"
)

plt.title("Customer Churn by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Number of Customers")
plt.xticks(rotation=15)
plt.show()

#Churn rate by contract type
contract_churn_rate = (
    df.groupby("Contract")["Churn"]
    .apply(lambda x: (x == "Yes").mean() * 100)
    .sort_values(ascending=False)
)

print(contract_churn_rate)

plt.figure(figsize=(8, 5))

contract_churn_rate.plot(kind="bar")

plt.title("Churn Rate by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Churn Rate (%)")
plt.xticks(rotation=15)
plt.show()

#Churn by tenure group
tenure_churn = pd.crosstab(
    df["TenureGroup"],
    df["Churn"]
)

print(tenure_churn)

tenure_order = [
    "0-1 Year",
    "1-2 Years",
    "2-4 Years",
    "4+ Years"
]

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x="TenureGroup",
    hue="Churn",
    order=tenure_order
)

plt.title("Customer Churn by Tenure Group")
plt.xlabel("Tenure Group")
plt.ylabel("Number of Customers")
plt.show()

#Churn by payment method
payment_churn_rate = (
    df.groupby("PaymentMethod")["Churn"]
    .apply(lambda x: (x == "Yes").mean() * 100)
    .sort_values(ascending=False)
)

print(payment_churn_rate)

plt.figure(figsize=(10, 6))

payment_churn_rate.plot(kind="bar")

plt.title("Churn Rate by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Churn Rate (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

payment_churn_rate.plot(kind="bar")

plt.title("Churn Rate by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Churn Rate (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Churn by internet service
internet_churn = pd.crosstab(
    df["InternetService"],
    df["Churn"]
)

print(internet_churn)

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x="InternetService",
    hue="Churn"
)

plt.title("Customer Churn by Internet Service")
plt.xlabel("Internet Service")
plt.ylabel("Number of Customers")
plt.show()

#Monthly charges by churn status
monthly_charges_churn = (
    df.groupby("Churn")["MonthlyCharges"]
    .mean()
)

print(monthly_charges_churn)

plt.figure(figsize=(7, 5))

sns.boxplot(
    data=df,
    x="Churn",
    y="MonthlyCharges"
)

plt.title("Monthly Charges by Churn Status")
plt.xlabel("Churn")
plt.ylabel("Monthly Charges")
plt.show()

#Tenure by churn status
plt.figure(figsize=(7, 5))

sns.boxplot(
    data=df,
    x="Churn",
    y="tenure"
)

plt.title("Customer Tenure by Churn Status")
plt.xlabel("Churn")
plt.ylabel("Tenure in Months")
plt.show()

#Churn by gender
gender_churn_rate = (
    df.groupby("gender")["Churn"]
    .apply(lambda x: (x == "Yes").mean() * 100)
)

print(gender_churn_rate)

#Churn by senior citizen status
senior_churn_rate = (
    df.groupby("SeniorCitizen")["Churn"]
    .apply(lambda x: (x == "Yes").mean() * 100)
)

print(senior_churn_rate)

plt.figure(figsize=(6, 5))

sns.countplot(
    data=df,
    x="SeniorCitizen",
    hue="Churn"
)

plt.title("Customer Churn by Senior Citizen Status")
plt.xlabel("Senior Citizen")
plt.ylabel("Number of Customers")
plt.show()

#Churn by tech support
tech_support_churn = (
    df.groupby("TechSupport")["Churn"]
    .apply(lambda x: (x == "Yes").mean() * 100)
    .sort_values(ascending=False)
)

print(tech_support_churn)

#Churn by online security
security_churn = (
    df.groupby("OnlineSecurity")["Churn"]
    .apply(lambda x: (x == "Yes").mean() * 100)
    .sort_values(ascending=False)
)

print(security_churn)

#Correlation Analysis
#Step 30: Create a numeric churn column
df["ChurnValue"] = df["Churn"].map({
    "No": 0,
    "Yes": 1
})

#Correlation heatmap
numeric_columns = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges",
    "ChurnValue"
]

correlation = df[numeric_columns].corr()

plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

#Customer Segment Analysis
#Step 32: Identify high-value churned customers

#For this project, you can define a high-value customer as someone with above-average TotalCharges.

average_total_charges = df["TotalCharges"].mean()

high_value_churned = df[
    (df["TotalCharges"] > average_total_charges) &
    (df["Churn"] == "Yes")
]

print(
    "High-Value Churned Customers:",
    len(high_value_churned)
)

high_value_churned[
    [
        "customerID",
        "tenure",
        "Contract",
        "MonthlyCharges",
        "TotalCharges",
        "PaymentMethod"
    ]
].head(10)

#Create KPI summary
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Customers",
        "Churned Customers",
        "Retained Customers",
        "Churn Rate (%)",
        "Retention Rate (%)",
        "Average Monthly Charges"
    ],
    "Value": [
        total_customers,
        churned_customers,
        retained_customers,
        round(churn_rate, 2),
        round(retention_rate, 2),
        round(average_monthly_charges, 2)
    ]
})

kpi_summary

df.to_csv(
    "cleaned_telco_customer_churn.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

from google.colab import files

files.download(
    "cleaned_telco_customer_churn.csv"
)